
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const Admin = lazy(() => import("./pages/Admin.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const MemeText = lazy(() => import("./pages/MemeText.tsx"));
const MotionVideo = lazy(() => import("./pages/MotionVideo.tsx"));
const Preview = lazy(() => import("./pages/Preview.tsx"));
const Upload = lazy(() => import("./pages/Upload.tsx"));
const ViralAdGenerator = lazy(() => import("./pages/ViralAdGenerator.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/admin", element: <Admin />},
	{ path: "/", element: <App />},
	{ path: "/meme-text", element: <MemeText />},
	{ path: "/memetext", element: <MemeText />},
	{ path: "/motion-video", element: <MotionVideo />},
	{ path: "/motionvideo", element: <MotionVideo />},
	{ path: "/preview", element: <Preview />},
	{ path: "/upload", element: <Upload />},
	{ path: "/viral-ad-generator", element: <ViralAdGenerator />},
	{ path: "/viraladgenerator", element: <ViralAdGenerator />},

];
